version: '3.8'

services:
  db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "python wait_for_db.py db 3306 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  db_data: